### ISSUE TITLE
False positive in Abbot and Costello

### ISSUE THREAD

**Issue by xsawyerx** [lancew/Perl-Critic-Policy-Perlsecret#14]
I got the following error:

    [Perlsecret] Perlsecret risk. Abbott and Costello  at lib/Dancer2/Core/App.pm line 461,
    near 'return $self->_has_session'

The code in question:

```
    return $self->_has_session
        || ( $self->cookie( $engine->cookie_name )
             && !$self->has_destroyed_session );
```

The rule should only check for empty parenthesis, not ones with content. Didn't spot this until I started using this policy more and more. Sorry about that. :)

**Comment by lancew** [comment]
Pushed an update. :-)
